// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AttendanceCheck is the result of the pre-submit "is this capture already
 * in the ledger?" probe — GET /api/officer/attendance?activity=&occurredAt=.
 * Count is the number of matching `source='parse'` ep_ledger rows within a
 * ±60 min window of occurredAt (2026-09-23 — was an exact match, which
 * missed a second officer's own capture of the same raid); Exists is
 * Count > 0. EnteredBy/OccurredAt describe the earliest matching row, and
 * EventLead is set when this raid moment already has one, so the app can
 * name who beat this officer to it instead of just showing a count.
 */
export interface AttendanceCheck {
    "exists": boolean;
    "count": number;
    "enteredBy"?: string;
    "occurredAt"?: string;
    "eventLead"?: EventLeadInfo | null;
}

export interface AttendanceResponse {
    "inserted": number;
    "eventLeadInserted": boolean;

    /**
     * The character Event Lead was actually awarded to (may be an alt's
     * main, not whatever name was typed) — empty unless EventLeadInserted.
     */
    "eventLeadCharacterName"?: string;
    "unmatched": string[] | null;

    /**
     * Names skipped because they resolved to a player already awarded this
     * activity/timestamp elsewhere in the submission, or already on
     * ep_ledger from an earlier submission of the same capture (PLAN.md
     * §4h-1) — surfaced rather than silently dropped, same reasoning as
     * Unmatched.
     */
    "duplicates": string[] | null;

    /**
     * Set when awardEventLead was true but this raid moment (±60 min, any
     * recipient) already had one — 2026-09-23, the two-officers-one-raid
     * bug. The attendance rows above still land; only the SECOND award was
     * skipped.
     */
    "eventLeadSkipped"?: EventLeadInfo | null;
}

/**
 * BankEqAccount is one "these characters share a real EQ login" group
 * (bank_eq_accounts) — see src/lib/bank/sync.ts on the site.
 */
export interface BankEqAccount {
    "id": number;
    "label": string;
    "sharedBankHolderCharacterId": number;
    "characterIds": number[] | null;
}

/**
 * BankImportInfo is the last sync recorded for one holder character.
 */
export interface BankImportInfo {
    "characterId": number;
    "sourceFile": string;
    "rowCount": number;
    "reportsSharedBank": boolean;
    "uploadedByName": string;
    "createdAt": string;
}

/**
 * BankSyncDiff is one holder's result — what changed for a real sync, or
 * what would change for a dry-run preview.
 */
export interface BankSyncDiff {
    "characterId": number;
    "added": BankSyncDiffRow[] | null;
    "removed": BankSyncDiffRow[] | null;
    "changed": {"before": BankSyncDiffRow, "after": BankSyncDiffRow}[] | null;
    "unchanged": number;
}

/**
 * BankSyncDiffRow is one row of a diff — added/removed/changed.
 */
export interface BankSyncDiffRow {
    "container": string;
    "slotIndex": number;
    "itemName": string;
    "quantity": number;
}

export interface BidEntry {
    "characterName": string;
    "tier": string;
    "occurredAt": string;
    "isWinner": boolean;
}

export interface BidsResponse {
    "lootEventId": number;
    "inserted": number;
    "unmatched": string[] | null;
    "invalidTiers": string[] | null;

    /**
     * Set by SubmitBidsChecked when the site returned 409 "already
     * recorded" instead of writing anything — the caller shows the message
     * and offers a "Record anyway" that resends with ConfirmDuplicate.
     */
    "duplicate"?: boolean;
    "duplicateMessage"?: string;

    /**
     * True when the site recognized SubmissionID as an already-recorded
     * round and handed back that original result instead of writing
     * anything new — a successful retry, not a fresh submission. GP was
     * charged once, on whichever attempt actually landed first.
     */
    "replay"?: boolean;
}

export interface Character {
    "id": number;
    "name": string;
    "charType": string;
    "mainCharacterId": number | null;
    "status": string;
    "mainCharacterName": string | null;
    "priorityRating": number | null;
}

/**
 * EventLeadInfo names who already holds Event Lead for a raid moment —
 * returned by both the pre-submit probe (AttendanceCheck.EventLead) and the
 * submit response (AttendanceResponse.EventLeadSkipped).
 */
export interface EventLeadInfo {
    "recipientName": string;
    "enteredByName"?: string;
}

/**
 * LedgerRow covers both EP rows (Activity set, ItemName/Tier empty) and
 * GP rows (ItemName/Tier set, Activity empty) — same union the site's own
 * /epgp/ledger page renders, just as JSON instead of a table.
 */
export interface LedgerRow {
    "id": number;
    "characterName": string;
    "occurredAt": string;
    "activity"?: string;
    "itemName"?: string;
    "tier"?: string;
    "points": number;
    "note": string | null;
    "source": string;
    "enteredByName": string | null;
}

/**
 * ManualEntryRequest mirrors seekers-tracker's InsertLedgerEntryInput
 * exactly (src/lib/epgp/ledger-entry.ts) — ItemName is only meaningful
 * (and only sent) for Kind "gp"; Zone only for Kind "ep" (e.g. a raid-lead
 * "Event Lead" award naming which raid it was for), same as the
 * Attendance tab already sends.
 */
export interface ManualEntryRequest {
    "kind": string;
    "characterId": number;
    "activity"?: string;
    "tier"?: string;
    "itemName"?: string;
    "zone"?: string;
    "points": number;
    "occurredAt": string;
    "note": string;
}

export interface PointValue {
    "activity": string;
    "points": number;
}

/**
 * SaveBankAccountRequest creates (ID zero) or updates (ID set) an EQ
 * account group.
 */
export interface SaveBankAccountRequest {
    "id"?: number;
    "label": string;
    "characterIds": number[] | null;
    "sharedBankHolderCharacterId": number;
}

/**
 * Settings mirrors seekers-tracker's leader-tunable EPGP constants
 * (PLAN.md §4i) — EPCapPerCycle, MinAttendance, and the decay rates are
 * never hardcoded here; this app is a thin capture client and the website
 * owns the rules. The site returns every value as a string (epgp_settings
 * stores everything as text so new settings never need a schema change);
 * DecayModel stays a string (legacy|global), everything else parses to a
 * float64 for arithmetic/comparison on this side.
 */
export interface Settings {
    "EPDecay": number;
    "GPDecay": number;
    "BaseEP": number;
    "BaseGP": number;
    "EPCapPerCycle": number;
    "MinAttendance": number;
    "DecayModel": string;
}

export interface TotalsRow {
    "id": number;
    "name": string;
    "charType": string;
    "status": string;
    "mainCharacterName": string | null;
    "ep": number | null;
    "gp": number | null;
    "epDecay": number | null;
    "gpDecay": number | null;
    "priorityRating": number | null;
}
