// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AttendanceResponse {
    "inserted": number;
    "unmatched": string[] | null;

    /**
     * Names skipped because they resolved to a player already awarded this
     * activity/timestamp elsewhere in the submission, or already on
     * ep_ledger from an earlier submission of the same capture (PLAN.md
     * §4h-1) — surfaced rather than silently dropped, same reasoning as
     * Unmatched.
     */
    "duplicates": string[] | null;
}

export interface BidEntry {
    "characterName": string;
    "tier": string;
    "occurredAt": string;
    "isWinner": boolean;
}

export interface BidsResponse {
    "lootEventId": number;
    "inserted": number;
    "unmatched": string[] | null;
    "invalidTiers": string[] | null;

    /**
     * Set by SubmitBidsChecked when the site returned 409 "already
     * recorded" instead of writing anything — the caller shows the message
     * and offers a "Record anyway" that resends with ConfirmDuplicate.
     */
    "duplicate"?: boolean;
    "duplicateMessage"?: string;
}

export interface Character {
    "id": number;
    "name": string;
    "charType": string;
    "mainCharacterId": number | null;
    "status": string;
    "mainCharacterName": string | null;
    "priorityRating": number | null;
}

/**
 * LedgerRow covers both EP rows (Activity set, ItemName/Tier empty) and
 * GP rows (ItemName/Tier set, Activity empty) — same union the site's own
 * /epgp/ledger page renders, just as JSON instead of a table.
 */
export interface LedgerRow {
    "id": number;
    "characterName": string;
    "occurredAt": string;
    "activity"?: string;
    "itemName"?: string;
    "tier"?: string;
    "points": number;
    "note": string | null;
    "source": string;
    "enteredByName": string | null;
}

/**
 * ManualEntryRequest mirrors seekers-tracker's InsertLedgerEntryInput
 * exactly (src/lib/epgp/ledger-entry.ts) — ItemName is only meaningful
 * (and only sent) for Kind "gp"; Zone only for Kind "ep" (e.g. a raid-lead
 * "Event Lead" award naming which raid it was for), same as the
 * Attendance tab already sends.
 */
export interface ManualEntryRequest {
    "kind": string;
    "characterId": number;
    "activity"?: string;
    "tier"?: string;
    "itemName"?: string;
    "zone"?: string;
    "points": number;
    "occurredAt": string;
    "note": string;
}

export interface PointValue {
    "activity": string;
    "points": number;
}

/**
 * Settings mirrors seekers-tracker's leader-tunable EPGP constants
 * (PLAN.md §4i) — EPCapPerCycle, MinAttendance, and the decay rates are
 * never hardcoded here; this app is a thin capture client and the website
 * owns the rules. The site returns every value as a string (epgp_settings
 * stores everything as text so new settings never need a schema change);
 * DecayModel stays a string (legacy|global), everything else parses to a
 * float64 for arithmetic/comparison on this side.
 */
export interface Settings {
    "EPDecay": number;
    "GPDecay": number;
    "BaseEP": number;
    "BaseGP": number;
    "EPCapPerCycle": number;
    "MinAttendance": number;
    "DecayModel": string;
}

export interface TotalsRow {
    "id": number;
    "name": string;
    "charType": string;
    "status": string;
    "mainCharacterName": string | null;
    "ep": number | null;
    "gp": number | null;
    "epDecay": number | null;
    "gpDecay": number | null;
    "priorityRating": number | null;
}
