// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Settings {
    "apiKey": string;

    /**
     * LogPath is the log file currently being watched. When GameDir is set
     * and ManualLogPath is false, the app keeps this pointed at whichever
     * character's eqlog is being written to right now (see internal/eqlogs);
     * otherwise it's whatever file the officer picked by hand.
     */
    "logPath": string;

    /**
     * GameDir is the EverQuest install folder (or its Logs subfolder). When
     * set, the app auto-detects the active character's log under it and
     * follows character swaps mid-raid, instead of pinning one file.
     */
    "gameDir"?: string;

    /**
     * ManualLogPath is true when the officer picked a specific log file via
     * "Select Log File" rather than a game folder — the active-character
     * watcher then leaves LogPath alone so it doesn't override their choice.
     * Re-picking a game folder clears this.
     */
    "manualLogPath"?: boolean;

    /**
     * Whether the Bids tab watches the log and auto-starts a round when the
     * officer announces "<item> send tells". A pointer so "absent from the
     * file" (nil) reads as ON — the default — while an explicit false from
     * the Settings toggle stays off. Read it through AutoDetectBidsEnabled.
     */
    "autoDetectBids"?: boolean | null;
}
