// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CharacterLog is one eqlog_<Character>_<server>.txt found under a game
 * directory's Logs folder.
 */
export interface CharacterLog {
    "character": string;
    "server": string;
    "path": string;
    "modifiedAt": string;
    "size": number;
}
