// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Info {
    "current": string;
    "latest": string;
    "available": boolean;
    "url": string;
}
