// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App holds the running application's state: an in-memory cache of the
 * selected log file, kept in sync with config.json (see ServiceStartup and
 * SelectLogFile) so it survives restarts and rebuilds instead of forcing
 * a re-pick every time the app relaunches; and a cache of the site's
 * leader-tunable EPGP settings (PLAN.md §4i, task 1.6) — this app never
 * hardcodes the EP cap, minimum attendance, or decay rates, it fetches
 * them.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as officerapi$0 from "./internal/officerapi/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AllowQuit(): $CancellablePromise<boolean> {
    return $Call.ByID(2877184241);
}

/**
 * AppVersion is the running build's version string — "vX.Y.Z" for a
 * tagged release (ldflags -X main.Version), "dev" for a local build.
 * Shown at the foot of the Settings screen.
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1970741496);
}

/**
 * ArchiveAndTrimLog zips the given log file's ENTIRE current content to a
 * verified backup next to it, then trims the live file down to the last
 * logmaint.KeepDays. Refuses (mirroring pq-companion, which added this
 * after a real corruption-risk bug) if the file was written to within
 * logmaint.LiveWriteWindow — the EverQuest client holds its own write
 * handle open on the log for the whole play session, so the officer has
 * to actually camp out of the zone before this is safe to run.
 * 
 * path is normally the currently-watched log (a.currentLogPath()), but
 * any log eqlogs.Discover found under the configured game folder can be
 * targeted the same way — pruning one that isn't actively being tailed
 * carries none of the "release our own handle before renaming" hazard
 * below, since only the actively-watched path ever has an open handle
 * from this app's own tailer.
 */
export function ArchiveAndTrimLog(path: string): $CancellablePromise<$models.ArchiveResultView> {
    return $Call.ByID(2609359236, path);
}

/**
 * CaptureAttendance re-reads the log file and returns the MOST RECENT
 * "/who" or "/who guild" snapshot (both produce the same "Players on
 * EverQuest:" block parse.ParseAttendance reads) — a raid night can have
 * several (start/mid/end checks), and the officer only ever wants the
 * latest one to record right now, same as the sketch's single "Attendance"
 * capture button implies.
 */
export function CaptureAttendance(): $CancellablePromise<$models.AttendanceResult> {
    return $Call.ByID(612176974);
}

/**
 * CaptureBids opens a live round: name the item, click once (or let the
 * "send tells" watcher do it), and the round starts tracking.
 * 
 * announcedAt is the RFC3339 timestamp of the specific "<item> send tells"
 * line the watcher detected (empty when the officer clicked Capture Bids by
 * hand). When set, it IS the window start — trusting the exact line the
 * watcher found, rather than re-deriving with parse.FindAnnouncementStart,
 * which merges announcements within a 10-min gap and so would fold a
 * re-announcement back into a just-finished round. The manual path still
 * uses FindAnnouncementStart. Either way the start is clamped to roundFloor
 * (bumped every time a round ends) so a finished round's bids can't leak
 * into the next one.
 * 
 * From there the poller both pushes each new tell to the site's live view
 * and re-emits the growing round to this app on "bids:round" until
 * EndBidRound or SubmitBids. The returned BidRound is the first frame; it's
 * marked Live.
 */
export function CaptureBids(itemName: string, announcedAt: string): $CancellablePromise<$models.BidRound> {
    return $Call.ByID(1880411077, itemName, announcedAt);
}

/**
 * SubmitAttendance sends exactly the names the officer is left with after
 * editing/removing rows in the Attendance tab — same "submit what's on
 * screen" contract as the Copy-to-clipboard button next to it, just to the
 * site's ledger instead of the clipboard.
 * CheckAttendanceRecorded probes whether an (activity, occurredAt) capture
 * is already on the ledger, so the Attendance tab's submit-confirmation can
 * flag "already recorded — this would be a no-op" before the officer
 * commits (sim feedback 2026-09-09). Best-effort at the call site: a
 * failure here (older site without the GET route, offline) just means no
 * pre-warning, not a blocked submit.
 */
export function CheckAttendanceRecorded(activity: string, occurredAt: string): $CancellablePromise<officerapi$0.AttendanceCheck> {
    return $Call.ByID(1251765916, activity, occurredAt);
}

/**
 * CheckForUpdate compares this build's embedded Version against the
 * repo's latest GitHub release, for the startup "you're on an old build"
 * banner. Errors here (no network, GitHub unreachable) are non-fatal to
 * the rest of the app — the frontend just skips showing a banner. An
 * unversioned "dev" build never reports an update available — there's
 * nothing meaningful to compare a local build against.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(2347956003);
}

/**
 * ClearAllBankDesignations wholesale-clears an owner's designations — the
 * one bulk action that's a real "replace with nothing" rather than
 * add/remove, since "clear everything" has no "leave other flags alone"
 * nuance to preserve.
 */
export function ClearAllBankDesignations(characterID: number, eqAccountID: number): $CancellablePromise<void> {
    return $Call.ByID(3085203971, characterID, eqAccountID);
}

/**
 * ClearAllRolls hides every currently-tracked roll session — a fresh
 * /random anywhere starts a brand-new one. Nothing is deleted from the
 * log itself; this only affects what the Rolls tab shows.
 */
export function ClearAllRolls(): $CancellablePromise<void> {
    return $Call.ByID(2552100915);
}

/**
 * CreateBankMule creates a brand-new mule character, attached to the
 * calling officer's own account server-side — for an export whose
 * filename matches no roster character yet.
 */
export function CreateBankMule(name: string): $CancellablePromise<officerapi$0.Character> {
    return $Call.ByID(3757296726, name);
}

/**
 * CurrentLogCharacter returns the character name the currently-watched log
 * file belongs to (from its eqlog_<Character>_<server>.txt filename), or ""
 * if no log is selected yet. Same helper startLiveBidPush already uses for
 * "collected by" on the live-bids board — exposed here so the Attendance
 * tab can prefill the Event Lead field with "probably you" instead of
 * leaving it blank and only explaining the default in a tooltip
 * (post-live-test-1 feedback, 2026-09-23: an officer wasn't sure where to
 * set it). Still just a prefill — the officer can change or clear it, and
 * the site's own default (the API key owner's current main) is unaffected.
 */
export function CurrentLogCharacter(): $CancellablePromise<string> {
    return $Call.ByID(2012932359);
}

export function DeleteBankEqAccount(id: number): $CancellablePromise<void> {
    return $Call.ByID(2002968089, id);
}

/**
 * DetectedLogs re-scans the configured game folder — backs the Settings
 * character list's Refresh button. Empty (not an error) if no game folder
 * is set yet.
 */
export function DetectedLogs(): $CancellablePromise<$models.GameDirInfo> {
    return $Call.ByID(2742340152);
}

/**
 * DiscardBidRound throws away the current round without recording it —
 * clears it off the site's live view and drops local round state. Wired to
 * the Bids tab's "Discard" button.
 */
export function DiscardBidRound(): $CancellablePromise<void> {
    return $Call.ByID(536756724);
}

/**
 * EndBidRound stops the live poller and returns one last, frozen scan for
 * the officer to edit and submit. It does NOT clear the site's round — the
 * bids stay visible on /live-bids while the officer picks a winner, and
 * SubmitBids then flips that round to "resolved" (Phase 16). If the officer
 * abandons the round instead, DiscardBidRound clears it, or the DO's idle
 * sweep drops it after ~5 min. Idempotent-ish: with no round open it just
 * returns an empty, non-live BidRound.
 */
export function EndBidRound(): $CancellablePromise<$models.BidRound> {
    return $Call.ByID(1893240499);
}

/**
 * FetchGuildSettings does a live re-fetch of the site's leader-tunable
 * EPGP settings and updates the in-memory cache startup() seeded — "fetch
 * at startup and re-validate at submit" (PLAN.md §4i, task 1.6). Nothing
 * calls this before a submit yet (there's no threshold to check against
 * until task 4.4's minimum-attendance pre-check lands), but the Settings
 * tab calls it to show the officer the guild's current numbers, and it's
 * the hook 4.4 attaches to rather than trusting a settings snapshot that
 * might be from hours ago.
 */
export function FetchGuildSettings(): $CancellablePromise<officerapi$0.Settings> {
    return $Call.ByID(2677897443);
}

/**
 * FetchKnownItems backs the Bids item-name field's autocomplete — every
 * item_name the site's gp_ledger has ever charged GP for (see
 * /api/officer/items). There's no separate items catalog; typing a new
 * item just means it'll suggest itself for the next officer once this
 * bid is submitted.
 */
export function FetchKnownItems(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2424807710);
}

export function FetchLedger(kind: string, query: string, page: number): $CancellablePromise<$models.LedgerPage> {
    return $Call.ByID(516147338, kind, query, page);
}

export function FetchPointValues(): $CancellablePromise<$models.PointValues> {
    return $Call.ByID(212557849);
}

/**
 * FetchRoster backs the Main-character and Priority columns on both the
 * Attendance and Bids tables — the frontend fetches this once and
 * resolves each editable row's name against it live (client-side), so a
 * typo'd name fixed in the table updates its Main/Priority immediately
 * without another round trip.
 */
export function FetchRoster(): $CancellablePromise<officerapi$0.Character[] | null> {
    return $Call.ByID(586469672);
}

export function FetchTotals(query: string): $CancellablePromise<officerapi$0.TotalsRow[] | null> {
    return $Call.ByID(2327640120, query);
}

/**
 * GetActiveLogInfo runs the heavier size+oldest/newest-entry scan against
 * the currently-watched log — the Settings tab's "Check Log File" step.
 * Errors if no log file is selected yet.
 */
export function GetActiveLogInfo(): $CancellablePromise<$models.LogFileInfoView> {
    return $Call.ByID(2183016829);
}

/**
 * GetLiveBidPushStatus returns the current round's delivery status, or a
 * zero value when no round is live.
 */
export function GetLiveBidPushStatus(): $CancellablePromise<$models.LiveBidPushStatus> {
    return $Call.ByID(819017598);
}

export function GetLogMaintenanceThresholds(): $CancellablePromise<$models.LogMaintenanceThresholds> {
    return $Call.ByID(1298552278);
}

export function GetLogPath(): $CancellablePromise<string> {
    return $Call.ByID(371917464);
}

/**
 * GetLogTailStatus returns the current tailer's stats, or a zero-value
 * LogTailStatus (not an error) when no log file is selected yet.
 */
export function GetLogTailStatus(): $CancellablePromise<$models.LogTailStatus> {
    return $Call.ByID(3575400447);
}

/**
 * GetRollSessions returns every /random roll-off currently tracked,
 * newest-first. Called on a plain frontend poll — nothing here involves
 * the network, so there's no latency to hide behind a push/event
 * mechanism the way Bids' live-push to the site needed.
 */
export function GetRollSessions(lookbackHours: number): $CancellablePromise<$models.RollSessionView[] | null> {
    return $Call.ByID(1961889629, lookbackHours);
}

/**
 * GetRollWinnerRule returns the current "highest" | "lowest" preference.
 */
export function GetRollWinnerRule(): $CancellablePromise<string> {
    return $Call.ByID(1912962457);
}

export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2554697378);
}

export function HasUnsavedWork(): $CancellablePromise<boolean> {
    return $Call.ByID(2769043346);
}

/**
 * InstallUpdate downloads and verifies the release CheckForUpdate already
 * found (DownloadAndInstall — digest checked before anything is staged,
 * same "verify before swapping anything in" guarantee Phase 7.2 had), then
 * Restart spawns a helper process to swap the staged download into place
 * and relaunch, quitting this process itself. Config lives outside the
 * binary (os.UserConfigDir(), PLAN.md §7 Phase 7.3) so the swap can't
 * touch the officer's saved API key or log path.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2443992793);
}

/**
 * ItemLink renders itemName as an in-game clickable item link (see
 * internal/items.Link) for the Bids tab's grats message, so it pastes into
 * guild/raid chat the same way a real linked item does instead of as plain
 * text. Falls back to the plain name unchanged when the item can't be
 * matched (items.Match — same typo-tolerant lookup the announcement
 * watcher uses) — the officer still gets a usable grats line, just without
 * the clickable link.
 */
export function ItemLink(itemName: string): $CancellablePromise<string> {
    return $Call.ByID(2451796390, itemName);
}

/**
 * LinkCharacter resolves an Attendance/Bids "no match" name against the
 * site roster: pass mainCharacterID to attach it as a new alt of that
 * main, or nil to add it as a brand-new main. The returned Character gets
 * merged into the frontend's already-fetched roster so the row resolves
 * immediately, without a full FetchRoster round trip.
 */
export function LinkCharacter(name: string, mainCharacterID: number | null): $CancellablePromise<officerapi$0.Character> {
    return $Call.ByID(3439719684, name, mainCharacterID);
}

/**
 * ListAttendanceSnapshots returns every "/who" / "/who guild" block in the
 * followed log from the last `lookbackHours` (0 -> default 12h, clamped to
 * [1, 72]), newest first, each as its own AttendanceResult. This backs the
 * Attendance tab's multi-capture workflow (post-live-test-1 LT-21/LT-22):
 * an officer captures at the start, middle, and end of a raid, keeps them
 * all on screen, then assigns and submits the ones they want after the
 * raid instead of mid-fight. Deduped by occurredAt; per-block warnings
 * attached to their block.
 */
export function ListAttendanceSnapshots(lookbackHours: number): $CancellablePromise<$models.AttendanceResult[] | null> {
    return $Call.ByID(3633388835, lookbackHours);
}

/**
 * MarkAllContainersGuild flags every listed container at once — "Mark all
 * Bank slots guild" / "Mark all Bags guild". Always uses add, never a
 * wholesale replace, so existing flags for OTHER containers (any kind,
 * any sub-item flags) are left alone — this is what fixes the
 * pre-2026-09-25 bug where a full-set replace silently dropped a flag on
 * a container missing from the current scan (e.g. a moved bag's now-empty
 * old slot).
 */
export function MarkAllContainersGuild(characterID: number, eqAccountID: number, containers: $models.BankContainerSeed[] | null): $CancellablePromise<void> {
    return $Call.ByID(2285521906, characterID, eqAccountID, containers);
}

/**
 * OpenAppKeyPage opens the site's app-key generation page in the
 * officer's default browser, so getting set up is "click this, paste the
 * key back in" rather than typing a URL by hand.
 */
export function OpenAppKeyPage(): $CancellablePromise<void> {
    return $Call.ByID(672229396);
}

/**
 * OpenReleasePage opens a GitHub release page (from CheckForUpdate's
 * Info.URL) in the officer's default browser, same pattern as
 * OpenAppKeyPage. Kept as a fallback next to InstallUpdate — if the
 * automatic swap fails (e.g. no write permission to the install
 * directory), the officer can still download and run the new exe by
 * hand.
 */
export function OpenReleasePage(url: string): $CancellablePromise<void> {
    return $Call.ByID(815420409, url);
}

/**
 * ParseAttendanceText is CaptureAttendance for text the officer pastes in
 * rather than the followed log file — the Manual Attendance form's "paste a
 * chunk of logs" path (a player-run quest's attendance reaches an officer
 * as a copied log snippet, not a /who the app was running for). Same
 * parser, same AttendanceResult shape. Unlike CaptureAttendance it merges
 * the names from EVERY "/who" block in the paste (deduped, first spelling
 * kept) rather than taking only the latest — a pasted snippet may hold two
 * or three checks and the officer wants everyone who was present — while
 * still reporting the latest block's time and zone. Every name stays
 * editable in the form before submit.
 */
export function ParseAttendanceText(raw: string): $CancellablePromise<$models.AttendanceResult> {
    return $Call.ByID(2891183248, raw);
}

/**
 * PreviewBankSync shows what a real sync would change, without writing
 * anything — same payload SubmitBankSync sends, just with dryRun=true.
 */
export function PreviewBankSync(): $CancellablePromise<$models.BankSyncResult> {
    return $Call.ByID(1954047010);
}

/**
 * RemoveRollSession hides one session from the Rolls tab entirely (a test
 * /random, or a range that wasn't actually a loot roll) and, like Stop,
 * forces the next roll in the same range to start fresh rather than
 * silently reappearing inside the hidden session.
 */
export function RemoveRollSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(1084244466, id);
}

/**
 * ResolveBankMove acts on one warning ScanGuildBank surfaced: "move" the
 * flag to where the bag/item was found (TargetContainer/TargetSlotIndex —
 * the warning's own SuggestedContainer/SuggestedSlotIndex, or an officer's
 * manual pick among Candidates), "keep" the flag where it is and accept
 * the current occupant as the new expected baseline (the officer decided
 * this position is correct as-is), or "unflag" it entirely. All three are
 * one remove-then-add designations call — the same call the checkbox
 * toggles use — so a warning is always resolved through the ordinary
 * designation path, never a special one.
 */
export function ResolveBankMove(input: $models.ResolveBankMoveInput): $CancellablePromise<void> {
    return $Call.ByID(1979867280, input);
}

/**
 * ResolveNoBidRound closes a reviewed round with no bids as rot loot. It does
 * not create a ledger row or winner: officers record any rot-loot GP charge
 * separately as a linked manual entry on the site.
 */
export function ResolveNoBidRound(itemName: string, roundID: string): $CancellablePromise<void> {
    return $Call.ByID(2519945105, itemName, roundID);
}

/**
 * SaveBankEqAccount creates or updates a "these characters share a real
 * EQ account" group — confirming (or overriding) one of ScanGuildBank's
 * SuggestedGroups, or a manual grouping.
 */
export function SaveBankEqAccount(req: officerapi$0.SaveBankAccountRequest): $CancellablePromise<number> {
    return $Call.ByID(2236179599, req);
}

export function SaveSettings(apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(1949631069, apiKey);
}

/**
 * ScanGuildBank discovers every Zeal inventory export in the configured
 * EverQuest folder, parses each, and matches it against the roster and
 * the site's current guild/personal designations — everything the Guild
 * Bank tab needs to render, including any detected bag/item moves. Never
 * caches between calls: a fresh scan is cheap (local files + two small
 * API calls) and always reflects the latest export off disk and the
 * latest designations another officer may have just saved.
 */
export function ScanGuildBank(): $CancellablePromise<$models.GuildBankState> {
    return $Call.ByID(4047222393);
}

/**
 * SelectGameDir asks for the EverQuest install folder (or its Logs
 * subfolder), then auto-detects the active character's log under it — the
 * PQ-Companion-style flow. From here on the app follows character swaps on
 * its own (startActiveLogWatch); the officer never re-picks a file when
 * they change toons for a raid. Clears the manual-file flag SelectLogFile
 * may have set.
 */
export function SelectGameDir(): $CancellablePromise<$models.GameDirInfo> {
    return $Call.ByID(3145746342);
}

export function SelectLogFile(): $CancellablePromise<string> {
    return $Call.ByID(597912695);
}

export function SetAllowQuit(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(1491183787, v);
}

/**
 * SetAnnouncementMatch switches how startAnnouncementWatch decides whether
 * a detected candidate is really an item — config.AnnouncementMatchItemDB
 * (the default: internal/items, with typo tolerance) or
 * config.AnnouncementMatchLegacy (the original Capitalized-words structural
 * check only, kept as a Settings fallback). Persisted, and restarts the
 * watcher immediately so the new mode applies without a relaunch.
 */
export function SetAnnouncementMatch(mode: string): $CancellablePromise<void> {
    return $Call.ByID(1659922297, mode);
}

/**
 * SetAttendanceUnsaved / SetBidsUnsaved are called by their panels whenever
 * their unsent-work state changes. HasUnsavedWork / AllowQuit / SetAllowQuit
 * are read/set by main.go's close hook.
 */
export function SetAttendanceUnsaved(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(1253126802, v);
}

/**
 * SetAutoDetectBids toggles the Bids-tab log watcher that auto-starts a
 * round when the officer announces "<item> send tells" in chat. Persisted,
 * and applied immediately (starts/stops the watcher this session too).
 */
export function SetAutoDetectBids(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(737290635, enabled);
}

export function SetBidsUnsaved(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(3851909227, v);
}

export function SetLogMaintenanceSettings(days: number, targetMB: number): $CancellablePromise<void> {
    return $Call.ByID(3412069079, days, targetMB);
}

/**
 * SetRollItemName labels a session with a free-text item name — unlike
 * Bids there's no "<item> send tells" announcement to parse the name out
 * of, so the officer types it.
 */
export function SetRollItemName(id: string, itemName: string): $CancellablePromise<void> {
    return $Call.ByID(3629064640, id, itemName);
}

/**
 * SetRollWinnerRule flips whether the top or bottom roll wins, applied
 * live to every session (a global preference, not per-session — matches
 * pq-companion). Persisted so it survives a restart.
 */
export function SetRollWinnerRule(rule: string): $CancellablePromise<void> {
    return $Call.ByID(233379877, rule);
}

/**
 * SetSetupComplete records that the officer has finished (or dismissed)
 * the first-run setup wizard, so it stops showing on launch. `false`
 * re-arms it (Settings' "Run setup again" doesn't need this — it opens the
 * wizard directly — but this keeps the flag honest if a caller wants to).
 */
export function SetSetupComplete(done: boolean): $CancellablePromise<void> {
    return $Call.ByID(353136387, done);
}

/**
 * StopRollSession freezes one session — its rolls are final as far as
 * this tracker is concerned — and forces the next /random in the same
 * range to start a NEW session rather than silently reopening this one.
 */
export function StopRollSession(id: string): $CancellablePromise<$models.RollSessionView> {
    return $Call.ByID(3649302074, id);
}

/**
 * eventLeadCharacterName names who Event Lead goes to when awardEventLead
 * is true; empty keeps the site's default (the API key owner's own
 * current main) — see officerapi.AttendanceRequest.EventLeadCharacterName.
 * The attendance-taker isn't always the actual raid leader, so the
 * Settings/confirm-dialog UI lets an officer name someone else instead of
 * only being able to toggle their own award on/off.
 */
export function SubmitAttendance(activity: string, occurredAt: string, names: string[] | null, zone: string, raidName: string, awardEventLead: boolean, eventLeadCharacterName: string): $CancellablePromise<officerapi$0.AttendanceResponse> {
    return $Call.ByID(2782717002, activity, occurredAt, names, zone, raidName, awardEventLead, eventLeadCharacterName);
}

/**
 * SubmitBankSync actually applies the sync.
 */
export function SubmitBankSync(): $CancellablePromise<$models.BankSyncResult> {
    return $Call.ByID(709946232);
}

/**
 * SubmitBids records every remaining row from the Bids tab as a bid (won
 * or lost) and charges GP to whichever one is flagged as the winner —
 * exactly one entry must have IsWinner set, which the frontend's
 * "Determine Winner" (tier first, then priority) picks by default but the
 * officer can override before calling this.
 * 
 * The site rejects a same-item finalize within 12h of an existing one as a
 * likely double-click (409). When confirmDuplicate is false that comes
 * back as resp.Duplicate=true + resp.DuplicateMessage with a nil error, so
 * the Bids tab can show "Record anyway"; calling again with
 * confirmDuplicate=true records it regardless (a boss really did drop the
 * same item twice in one night).
 * roundID is the round's own immutable id (BidRound.RoundID, task 3.1) —
 * supplied by the frontend rather than read from a.roundID because by the
 * time a PARKED round is submitted, a.roundID already belongs to whatever
 * round is current, not this one. Empty for a manual round or a build of
 * this app that predates the field; the site treats a missing id as "no
 * retry-idempotency for this submission" and falls back to its own
 * item/time heuristic, same as before this task.
 */
export function SubmitBids(itemName: string, roundID: string, entries: officerapi$0.BidEntry[] | null, confirmDuplicate: boolean): $CancellablePromise<officerapi$0.BidsResponse> {
    return $Call.ByID(3424067681, itemName, roundID, entries, confirmDuplicate);
}

/**
 * SubmitManualBid records a bid round the parser never captured — a tell
 * missed, or the app not running when the item dropped. It sends the same
 * payload SubmitBids does, but stamps every entry with the officer-supplied
 * occurredAt and runs none of the live-round bookkeeping
 * (roundItem/stopLiveBidPush) — there was no live round. Goes through
 * SubmitBidsChecked, so an item already recorded near this time comes back
 * as resp.Duplicate (with a message) rather than an error; the frontend
 * then offers "Record anyway", which resubmits with confirmDuplicate=true.
 */
export function SubmitManualBid(itemName: string, occurredAt: string, note: string, entries: officerapi$0.BidEntry[] | null, confirmDuplicate: boolean): $CancellablePromise<officerapi$0.BidsResponse> {
    return $Call.ByID(2335504918, itemName, occurredAt, note, entries, confirmDuplicate);
}

export function SubmitManualEntry(req: officerapi$0.ManualEntryRequest): $CancellablePromise<void> {
    return $Call.ByID(1930507941, req);
}

/**
 * SwitchBidRound (2026-09-10): a second "<item> send tells" landed while a
 * round was still live. The old flow made the officer click "Switch",
 * which DISCARDED the first round's bids and, until clicked, left the
 * second item's early tells unassigned. Now the Bids tab calls this the
 * moment the watcher fires: the open round is frozen with every tell up
 * to the new announcement, and the new item goes live from its
 * announcement time, so nothing said in between is lost. Tells after the
 * announcement belong to the new item — the guild's own convention; the
 * occasional straggler for the old item is what the review table's
 * "+ Add bid manually" is for. The parked round stays on the site's
 * board as-is (it's still a real, unfinished round); Submit later flips it
 * to resolved exactly as before.
 */
export function SwitchBidRound(nextItem: string, announcedAt: string): $CancellablePromise<$models.BidSwitchResult> {
    return $Call.ByID(1611946916, nextItem, announcedAt);
}

/**
 * TestConnection confirms the saved API key actually works by pulling the
 * roster (the same call the Attendance/Bids submit buttons eventually
 * validate names against) — the Settings screen's "did I set this up
 * right" check.
 */
export function TestConnection(): $CancellablePromise<number> {
    return $Call.ByID(1257240193);
}

/**
 * ToggleBankContainer flags/unflags an ENTIRE top-level container (the bag
 * and everything in it) for one character's personal Bank/General slots,
 * or (eqAccountID set instead) an EQ account's SharedBank slots — pass
 * exactly one of characterID/eqAccountID, mirroring the site's own
 * "exactly one owner" rule. expectedItemID/expectedItemName seed the
 * move-detection baseline immediately from the current scan when flagging
 * on, rather than waiting for the first sync to set it.
 */
export function ToggleBankContainer(characterID: number, eqAccountID: number, container: string, guild: boolean, expectedItemID: number, expectedItemName: string): $CancellablePromise<void> {
    return $Call.ByID(2973327450, characterID, eqAccountID, container, guild, expectedItemID, expectedItemName);
}

/**
 * ToggleBankItem flags/unflags ONE item inside a bag — finer-grained than
 * ToggleBankContainer (2026-09-25 officer feedback: "the ability to check
 * off the individual items within each bag in case things are spread
 * around"). Same owner/argument shape as ToggleBankContainer.
 */
export function ToggleBankItem(characterID: number, eqAccountID: number, container: string, slotIndex: number, guild: boolean, itemID: number, itemName: string): $CancellablePromise<void> {
    return $Call.ByID(2917885368, characterID, eqAccountID, container, slotIndex, guild, itemID, itemName);
}
