// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App holds the running application's state: an in-memory cache of the
 * selected log file, kept in sync with config.json (see ServiceStartup and
 * SelectLogFile) so it survives restarts and rebuilds instead of forcing
 * a re-pick every time the app relaunches; and a cache of the site's
 * leader-tunable EPGP settings (PLAN.md §4i, task 1.6) — this app never
 * hardcodes the EP cap, minimum attendance, or decay rates, it fetches
 * them.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as officerapi$0 from "./internal/officerapi/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CaptureAttendance re-reads the log file and returns the MOST RECENT
 * "/who" or "/who guild" snapshot (both produce the same "Players on
 * EverQuest:" block parse.ParseAttendance reads) — a raid night can have
 * several (start/mid/end checks), and the officer only ever wants the
 * latest one to record right now, same as the sketch's single "Attendance"
 * capture button implies.
 */
export function CaptureAttendance(): $CancellablePromise<$models.AttendanceResult> {
    return $Call.ByID(612176974);
}

/**
 * CaptureBids opens a live round: name the item, click once (or let the
 * "send tells" watcher do it), and the round starts tracking.
 * 
 * announcedAt is the RFC3339 timestamp of the specific "<item> send tells"
 * line the watcher detected (empty when the officer clicked Capture Bids by
 * hand). When set, it IS the window start — trusting the exact line the
 * watcher found, rather than re-deriving with parse.FindAnnouncementStart,
 * which merges announcements within a 10-min gap and so would fold a
 * re-announcement back into a just-finished round. The manual path still
 * uses FindAnnouncementStart. Either way the start is clamped to roundFloor
 * (bumped every time a round ends) so a finished round's bids can't leak
 * into the next one.
 * 
 * From there the poller both pushes each new tell to the site's live view
 * and re-emits the growing round to this app on "bids:round" until
 * EndBidRound or SubmitBids. The returned BidRound is the first frame; it's
 * marked Live.
 */
export function CaptureBids(itemName: string, announcedAt: string): $CancellablePromise<$models.BidRound> {
    return $Call.ByID(1880411077, itemName, announcedAt);
}

/**
 * CheckForUpdate compares this build's embedded Version against the
 * repo's latest GitHub release, for the startup "you're on an old build"
 * banner. Errors here (no network, GitHub unreachable) are non-fatal to
 * the rest of the app — the frontend just skips showing a banner. An
 * unversioned "dev" build never reports an update available — there's
 * nothing meaningful to compare a local build against.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(2347956003);
}

/**
 * DetectedLogs re-scans the configured game folder — backs the Settings
 * character list's Refresh button. Empty (not an error) if no game folder
 * is set yet.
 */
export function DetectedLogs(): $CancellablePromise<$models.GameDirInfo> {
    return $Call.ByID(2742340152);
}

/**
 * DiscardBidRound throws away the current round without recording it —
 * clears it off the site's live view and drops local round state. Wired to
 * the Bids tab's "Discard" button.
 */
export function DiscardBidRound(): $CancellablePromise<void> {
    return $Call.ByID(536756724);
}

/**
 * EndBidRound stops the live poller and returns one last, frozen scan for
 * the officer to edit and submit. It does NOT clear the site's round — the
 * bids stay visible on /live-bids while the officer picks a winner, and
 * SubmitBids then flips that round to "resolved" (Phase 16). If the officer
 * abandons the round instead, DiscardBidRound clears it, or the DO's idle
 * sweep drops it after ~5 min. Idempotent-ish: with no round open it just
 * returns an empty, non-live BidRound.
 */
export function EndBidRound(): $CancellablePromise<$models.BidRound> {
    return $Call.ByID(1893240499);
}

/**
 * FetchGuildSettings does a live re-fetch of the site's leader-tunable
 * EPGP settings and updates the in-memory cache startup() seeded — "fetch
 * at startup and re-validate at submit" (PLAN.md §4i, task 1.6). Nothing
 * calls this before a submit yet (there's no threshold to check against
 * until task 4.4's minimum-attendance pre-check lands), but the Settings
 * tab calls it to show the officer the guild's current numbers, and it's
 * the hook 4.4 attaches to rather than trusting a settings snapshot that
 * might be from hours ago.
 */
export function FetchGuildSettings(): $CancellablePromise<officerapi$0.Settings> {
    return $Call.ByID(2677897443);
}

/**
 * FetchKnownItems backs the Bids item-name field's autocomplete — every
 * item_name the site's gp_ledger has ever charged GP for (see
 * /api/officer/items). There's no separate items catalog; typing a new
 * item just means it'll suggest itself for the next officer once this
 * bid is submitted.
 */
export function FetchKnownItems(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2424807710);
}

export function FetchLedger(kind: string, query: string, page: number): $CancellablePromise<$models.LedgerPage> {
    return $Call.ByID(516147338, kind, query, page);
}

export function FetchPointValues(): $CancellablePromise<$models.PointValues> {
    return $Call.ByID(212557849);
}

/**
 * FetchRoster backs the Main-character and Priority columns on both the
 * Attendance and Bids tables — the frontend fetches this once and
 * resolves each editable row's name against it live (client-side), so a
 * typo'd name fixed in the table updates its Main/Priority immediately
 * without another round trip.
 */
export function FetchRoster(): $CancellablePromise<officerapi$0.Character[] | null> {
    return $Call.ByID(586469672);
}

export function FetchTotals(query: string): $CancellablePromise<officerapi$0.TotalsRow[] | null> {
    return $Call.ByID(2327640120, query);
}

export function GetLogPath(): $CancellablePromise<string> {
    return $Call.ByID(371917464);
}

export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2554697378);
}

/**
 * InstallUpdate downloads and verifies the release CheckForUpdate already
 * found (DownloadAndInstall — digest checked before anything is staged,
 * same "verify before swapping anything in" guarantee Phase 7.2 had), then
 * Restart spawns a helper process to swap the staged download into place
 * and relaunch, quitting this process itself. Config lives outside the
 * binary (os.UserConfigDir(), PLAN.md §7 Phase 7.3) so the swap can't
 * touch the officer's saved API key or log path.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2443992793);
}

/**
 * LinkCharacter resolves an Attendance/Bids "no match" name against the
 * site roster: pass mainCharacterID to attach it as a new alt of that
 * main, or nil to add it as a brand-new main. The returned Character gets
 * merged into the frontend's already-fetched roster so the row resolves
 * immediately, without a full FetchRoster round trip.
 */
export function LinkCharacter(name: string, mainCharacterID: number | null): $CancellablePromise<officerapi$0.Character> {
    return $Call.ByID(3439719684, name, mainCharacterID);
}

/**
 * OpenAppKeyPage opens the site's app-key generation page in the
 * officer's default browser, so getting set up is "click this, paste the
 * key back in" rather than typing a URL by hand.
 */
export function OpenAppKeyPage(): $CancellablePromise<void> {
    return $Call.ByID(672229396);
}

/**
 * OpenReleasePage opens a GitHub release page (from CheckForUpdate's
 * Info.URL) in the officer's default browser, same pattern as
 * OpenAppKeyPage. Kept as a fallback next to InstallUpdate — if the
 * automatic swap fails (e.g. no write permission to the install
 * directory), the officer can still download and run the new exe by
 * hand.
 */
export function OpenReleasePage(url: string): $CancellablePromise<void> {
    return $Call.ByID(815420409, url);
}

/**
 * ParseAttendanceText is CaptureAttendance for text the officer pastes in
 * rather than the followed log file — the Manual Attendance form's "paste a
 * chunk of logs" path (a player-run quest's attendance reaches an officer
 * as a copied log snippet, not a /who the app was running for). Same
 * parser, same AttendanceResult shape. Unlike CaptureAttendance it merges
 * the names from EVERY "/who" block in the paste (deduped, first spelling
 * kept) rather than taking only the latest — a pasted snippet may hold two
 * or three checks and the officer wants everyone who was present — while
 * still reporting the latest block's time and zone. Every name stays
 * editable in the form before submit.
 */
export function ParseAttendanceText(raw: string): $CancellablePromise<$models.AttendanceResult> {
    return $Call.ByID(2891183248, raw);
}

export function SaveSettings(apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(1949631069, apiKey);
}

/**
 * SelectGameDir asks for the EverQuest install folder (or its Logs
 * subfolder), then auto-detects the active character's log under it — the
 * PQ-Companion-style flow. From here on the app follows character swaps on
 * its own (startActiveLogWatch); the officer never re-picks a file when
 * they change toons for a raid. Clears the manual-file flag SelectLogFile
 * may have set.
 */
export function SelectGameDir(): $CancellablePromise<$models.GameDirInfo> {
    return $Call.ByID(3145746342);
}

export function SelectLogFile(): $CancellablePromise<string> {
    return $Call.ByID(597912695);
}

/**
 * SetAutoDetectBids toggles the Bids-tab log watcher that auto-starts a
 * round when the officer announces "<item> send tells" in chat. Persisted,
 * and applied immediately (starts/stops the watcher this session too).
 */
export function SetAutoDetectBids(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(737290635, enabled);
}

/**
 * SubmitAttendance sends exactly the names the officer is left with after
 * editing/removing rows in the Attendance tab — same "submit what's on
 * screen" contract as the Copy-to-clipboard button next to it, just to the
 * site's ledger instead of the clipboard.
 */
export function SubmitAttendance(activity: string, occurredAt: string, names: string[] | null, zone: string): $CancellablePromise<officerapi$0.AttendanceResponse> {
    return $Call.ByID(2782717002, activity, occurredAt, names, zone);
}

/**
 * SubmitBids records every remaining row from the Bids tab as a bid (won
 * or lost) and charges GP to whichever one is flagged as the winner —
 * exactly one entry must have IsWinner set, which the frontend's
 * "Determine Winner" (tier first, then priority) picks by default but the
 * officer can override before calling this.
 * 
 * The site rejects a same-item finalize within 12h of an existing one as a
 * likely double-click (409). When confirmDuplicate is false that comes
 * back as resp.Duplicate=true + resp.DuplicateMessage with a nil error, so
 * the Bids tab can show "Record anyway"; calling again with
 * confirmDuplicate=true records it regardless (a boss really did drop the
 * same item twice in one night).
 */
export function SubmitBids(itemName: string, entries: officerapi$0.BidEntry[] | null, confirmDuplicate: boolean): $CancellablePromise<officerapi$0.BidsResponse> {
    return $Call.ByID(3424067681, itemName, entries, confirmDuplicate);
}

/**
 * SubmitManualBid records a bid round the parser never captured — a tell
 * missed, or the app not running when the item dropped. It sends the same
 * payload SubmitBids does, but stamps every entry with the officer-supplied
 * occurredAt and runs none of the live-round bookkeeping
 * (roundItem/stopLiveBidPush) — there was no live round. Goes through
 * SubmitBidsChecked, so an item already recorded near this time comes back
 * as resp.Duplicate (with a message) rather than an error; the frontend
 * then offers "Record anyway", which resubmits with confirmDuplicate=true.
 */
export function SubmitManualBid(itemName: string, occurredAt: string, note: string, entries: officerapi$0.BidEntry[] | null, confirmDuplicate: boolean): $CancellablePromise<officerapi$0.BidsResponse> {
    return $Call.ByID(2335504918, itemName, occurredAt, note, entries, confirmDuplicate);
}

export function SubmitManualEntry(req: officerapi$0.ManualEntryRequest): $CancellablePromise<void> {
    return $Call.ByID(1930507941, req);
}

/**
 * TestConnection confirms the saved API key actually works by pulling the
 * roster (the same call the Attendance/Bids submit buttons eventually
 * validate names against) — the Settings screen's "did I set this up
 * right" check.
 */
export function TestConnection(): $CancellablePromise<number> {
    return $Call.ByID(1257240193);
}
