// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App holds the running application's state: an in-memory cache of the
 * selected log file, kept in sync with config.json (see ServiceStartup and
 * SelectLogFile) so it survives restarts and rebuilds instead of forcing
 * a re-pick every time the app relaunches; and a cache of the site's
 * leader-tunable EPGP settings (PLAN.md §4i, task 1.6) — this app never
 * hardcodes the EP cap, minimum attendance, or decay rates, it fetches
 * them.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as officerapi$0 from "./internal/officerapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updatecheck$0 from "./internal/updatecheck/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CaptureAttendance re-reads the log file and returns the MOST RECENT
 * "/who" or "/who guild" snapshot (both produce the same "Players on
 * EverQuest:" block parse.ParseAttendance reads) — a raid night can have
 * several (start/mid/end checks), and the officer only ever wants the
 * latest one to record right now, same as the sketch's single "Attendance"
 * capture button implies.
 */
export function CaptureAttendance(): $CancellablePromise<$models.AttendanceResult> {
    return $Call.ByID(612176974);
}

/**
 * CaptureBids takes a snapshot: name the item, click once, done. It finds
 * the most recent "<item> send tells" line the officer said themselves (at
 * or before now) and treats that as the window start — see
 * parse.FindAnnouncementStart — so there's no separate Start step to
 * forget before bids start coming in. Every candidate tell in that window
 * comes back, in log order, with later-from-the-same-character rows
 * marked Superseded (default) — never dropped, so the officer can override
 * which one actually wins before submitting.
 */
export function CaptureBids(itemName: string): $CancellablePromise<$models.BidRow[] | null> {
    return $Call.ByID(1880411077, itemName);
}

/**
 * CheckForUpdate compares this build's embedded Version against the
 * repo's latest GitHub release, for the startup "you're on an old build"
 * banner. Errors here (no network, GitHub unreachable) are non-fatal to
 * the rest of the app — the frontend just skips showing a banner.
 */
export function CheckForUpdate(): $CancellablePromise<updatecheck$0.Info> {
    return $Call.ByID(2347956003);
}

/**
 * FetchGuildSettings does a live re-fetch of the site's leader-tunable
 * EPGP settings and updates the in-memory cache startup() seeded — "fetch
 * at startup and re-validate at submit" (PLAN.md §4i, task 1.6). Nothing
 * calls this before a submit yet (there's no threshold to check against
 * until task 4.4's minimum-attendance pre-check lands), but the Settings
 * tab calls it to show the officer the guild's current numbers, and it's
 * the hook 4.4 attaches to rather than trusting a settings snapshot that
 * might be from hours ago.
 */
export function FetchGuildSettings(): $CancellablePromise<officerapi$0.Settings> {
    return $Call.ByID(2677897443);
}

/**
 * FetchKnownItems backs the Bids item-name field's autocomplete — every
 * item_name the site's gp_ledger has ever charged GP for (see
 * /api/officer/items). There's no separate items catalog; typing a new
 * item just means it'll suggest itself for the next officer once this
 * bid is submitted.
 */
export function FetchKnownItems(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2424807710);
}

export function FetchLedger(kind: string, query: string, page: number): $CancellablePromise<$models.LedgerPage> {
    return $Call.ByID(516147338, kind, query, page);
}

export function FetchPointValues(): $CancellablePromise<$models.PointValues> {
    return $Call.ByID(212557849);
}

/**
 * FetchRoster backs the Main-character and Priority columns on both the
 * Attendance and Bids tables — the frontend fetches this once and
 * resolves each editable row's name against it live (client-side), so a
 * typo'd name fixed in the table updates its Main/Priority immediately
 * without another round trip.
 */
export function FetchRoster(): $CancellablePromise<officerapi$0.Character[] | null> {
    return $Call.ByID(586469672);
}

export function FetchTotals(query: string): $CancellablePromise<officerapi$0.TotalsRow[] | null> {
    return $Call.ByID(2327640120, query);
}

export function GetLogPath(): $CancellablePromise<string> {
    return $Call.ByID(371917464);
}

export function GetSettings(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(2554697378);
}

/**
 * InstallUpdate downloads and verifies the latest release
 * (updatecheck.Apply — SHA-256 checked before anything is swapped in),
 * then relaunches: spawns a new process from the now-updated exe and
 * quits this one. Config lives outside the binary (os.UserConfigDir(),
 * PLAN.md §7 Phase 7.3) so the swap can't touch the officer's saved API
 * key or log path.
 */
export function InstallUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2443992793);
}

/**
 * LinkCharacter resolves an Attendance/Bids "no match" name against the
 * site roster: pass mainCharacterID to attach it as a new alt of that
 * main, or nil to add it as a brand-new main. The returned Character gets
 * merged into the frontend's already-fetched roster so the row resolves
 * immediately, without a full FetchRoster round trip.
 */
export function LinkCharacter(name: string, mainCharacterID: number | null): $CancellablePromise<officerapi$0.Character> {
    return $Call.ByID(3439719684, name, mainCharacterID);
}

/**
 * OpenAppKeyPage opens the site's app-key generation page in the
 * officer's default browser, so getting set up is "click this, paste the
 * key back in" rather than typing a URL by hand.
 */
export function OpenAppKeyPage(): $CancellablePromise<void> {
    return $Call.ByID(672229396);
}

/**
 * OpenReleasePage opens a GitHub release page (from CheckForUpdate's
 * Info.URL) in the officer's default browser, same pattern as
 * OpenAppKeyPage. Kept as a fallback next to InstallUpdate — if the
 * automatic swap fails (e.g. no write permission to the install
 * directory), the officer can still download and run the new exe by
 * hand.
 */
export function OpenReleasePage(url: string): $CancellablePromise<void> {
    return $Call.ByID(815420409, url);
}

export function SaveSettings(apiKey: string): $CancellablePromise<void> {
    return $Call.ByID(1949631069, apiKey);
}

export function SelectLogFile(): $CancellablePromise<string> {
    return $Call.ByID(597912695);
}

/**
 * SubmitAttendance sends exactly the names the officer is left with after
 * editing/removing rows in the Attendance tab — same "submit what's on
 * screen" contract as the Copy-to-clipboard button next to it, just to the
 * site's ledger instead of the clipboard.
 */
export function SubmitAttendance(activity: string, occurredAt: string, names: string[] | null): $CancellablePromise<officerapi$0.AttendanceResponse> {
    return $Call.ByID(2782717002, activity, occurredAt, names);
}

/**
 * SubmitBids records every remaining row from the Bids tab as a bid (won
 * or lost) and charges GP to whichever one is flagged as the winner —
 * exactly one entry must have IsWinner set, which the frontend's
 * "Determine Winner" (tier first, then priority) picks by default but the
 * officer can override before calling this.
 */
export function SubmitBids(itemName: string, entries: officerapi$0.BidEntry[] | null): $CancellablePromise<officerapi$0.BidsResponse> {
    return $Call.ByID(3424067681, itemName, entries);
}

export function SubmitManualEntry(req: officerapi$0.ManualEntryRequest): $CancellablePromise<void> {
    return $Call.ByID(1930507941, req);
}

/**
 * TestConnection confirms the saved API key actually works by pulling the
 * roster (the same call the Attendance/Bids submit buttons eventually
 * validate names against) — the Settings screen's "did I set this up
 * right" check.
 */
export function TestConnection(): $CancellablePromise<number> {
    return $Call.ByID(1257240193);
}
