// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as eqlogs$0 from "./internal/eqlogs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as officerapi$0 from "./internal/officerapi/models.js";

/**
 * ArchiveResultView is what one Archive & Trim run produced.
 */
export interface ArchiveResultView {
    "backupPath": string;
    "originalBytes": number;
    "keptBytes": number;
}

/**
 * AttendanceResult is what the frontend's Attendance tab renders into its
 * editable table — see the app's sketch (Name/Timestamp column layout).
 */
export interface AttendanceResult {
    "occurredAt": string;
    "zone": string;
    "names": string[] | null;
    "warnings": string[] | null;
}

/**
 * BankCharacterExport is one discovered export file, parsed and matched
 * against the roster + the site's current designation config.
 */
export interface BankCharacterExport {
    "character": string;
    "sourceFile": string;
    "exportedAt": string;
    "equipped": BankEquipped[] | null;
    "bags": BankContainer[] | null;
    "bank": BankContainer[] | null;
    "sharedBank": BankContainer[] | null;

    /**
     * SharedBankFingerprint is "" when this export's SharedBank is empty
     * (bankexport.SharedBankFingerprint) — used client-side only for the
     * account-grouping UI, not sent anywhere.
     */
    "sharedBankFingerprint": string;

    /**
     * RosterCharacterID is nil when no roster character matches this
     * export's filename — the Guild Bank tab offers "Create mule" for
     * these instead of showing containers to toggle.
     */
    "rosterCharacterId": number | null;
    "rosterCharType": string;
    "eqAccountId": number | null;

    /**
     * IsSharedBankHolder is true when this character is its account
     * group's designated SharedBank holder — only its SharedBank
     * containers can ever be flagged guild (SetBankDesignations rejects
     * the attempt otherwise, same rule the server enforces).
     */
    "isSharedBankHolder": boolean;
    "lastImport": officerapi$0.BankImportInfo | null;
}

/**
 * BankContainer is one top-level bag/bank slot, with Guild reflecting
 * whatever the website currently has designated for it — the toggle the
 * Guild Bank tab renders is just this field, read-modify-write via
 * SetBankDesignations.
 */
export interface BankContainer {
    "container": string;
    "kind": string;
    "number": number;
    "bagName": string;
    "capacity": number;
    "loose": boolean;
    "items": BankItem[] | null;
    "guild": boolean;
}

export interface BankEquipped {
    "location": string;
    "itemName": string;
}

/**
 * BankItem is one item inside a BankContainer, JSON-shaped for the
 * frontend (mirrors bankexport.SlotItem).
 */
export interface BankItem {
    "slotIndex": number;
    "category": string;
    "itemName": string;
    "itemId": number;
    "quantity": number;
}

/**
 * BankSuggestedGroup is an auto-detected "these characters look like the
 * same EQ account" suggestion (matching, non-empty SharedBank
 * fingerprints) for characters not already in a saved account group. The
 * officer confirms or ignores it via SaveBankEqAccount — nothing is
 * grouped automatically.
 */
export interface BankSuggestedGroup {
    "characterNames": string[] | null;
}

/**
 * BidRound is the state of one bid round the Bids tab renders. While Live
 * is true the poller re-emits this on "bids:round" every few seconds as
 * tells arrive; End Round & Review (EndBidRound) freezes it (Live false)
 * and the officer edits/submits from there. Wrapping the rows in a struct
 * rather than returning a bare []BidRow also sidesteps the Wails "extra
 * return value silently dropped" gotcha for the StartedAt/Live fields.
 */
export interface BidRound {
    "itemName": string;

    /**
     * The round's immutable id (remediation plan Phase 3 task 3.1) — see
     * App.roundID. Carried by the frontend through review/park and handed
     * back to SubmitBids so the final submission names the exact round it's
     * finalizing, not just an item name that could collide with a later
     * re-drop of the same item.
     */
    "roundId": string;
    "startedAt": string;
    "rows": BidRow[] | null;
    "live": boolean;
}

/**
 * BidRow is one candidate bid for the frontend's editable review table.
 */
export interface BidRow {
    "characterName": string;
    "occurredAt": string;
    "tier": string;
    "ambiguous": boolean;
    "rawMessage": string;

    /**
     * an earlier bid from the same character, kept visible but not the default winner
     */
    "superseded": boolean;

    /**
     * The bidder sent "cancel my bid" at or after placing this bid. The row
     * is kept and flagged, not dropped — the officer decides whether to
     * remove it (they meant it) or keep it (they re-bid, or were joking).
     */
    "cancelRequested": boolean;
}

/**
 * BidSwitchResult is what SwitchBidRound hands the Bids tab: the round
 * that was open, frozen and cut at the new announcement (Parked — for the
 * officer to review and submit after), and the new live round (Current).
 */
export interface BidSwitchResult {
    "parked": BidRound;
    "current": BidRound;
}

/**
 * GameDirInfo is what the Settings screen renders after the officer picks
 * their EverQuest folder: the folder itself, every character log found
 * under it, and which one the app is now following (the most recently
 * written — the character they're currently playing).
 */
export interface GameDirInfo {
    "gameDir": string;
    "logs": eqlogs$0.CharacterLog[] | null;
    "activePath": string;
    "activeChar": string;
    "activeServer": string;
}

export interface GuildBankState {
    "gameDir": string;
    "exports": BankCharacterExport[] | null;
    "accounts": officerapi$0.BankEqAccount[] | null;
    "suggestedGroups": BankSuggestedGroup[] | null;

    /**
     * Unmatched names a real export was found for but no roster character
     * matches — surfaced separately so the UI can offer "Create mule"
     * without cluttering Exports with an entry that has nothing to toggle.
     */
    "unmatchedCharacters": string[] | null;
}

/**
 * LedgerPage wraps FetchLedger's (rows, hasNext) pair into one
 * Wails-friendly return — same reason as PointValues above.
 */
export interface LedgerPage {
    "rows": officerapi$0.LedgerRow[] | null;
    "hasNext": boolean;
}

/**
 * LiveBidPushStatus backs a small "is this actually reaching the site"
 * indicator (remediation plan Phase 2 task 2.5) — the officer's own
 * "bids:round" view updates from the local log regardless, so without
 * this they'd have no way to notice the site delivery side is stuck
 * until a member says the live board looks wrong.
 */
export interface LiveBidPushStatus {
    "lastDeliveredAt": string;
    "pendingRetry": boolean;
    "lastError": string;
}

/**
 * LogFileInfoView is a size/date snapshot of one log file, backing the
 * Settings tab's log-maintenance section.
 */
export interface LogFileInfoView {
    "path": string;
    "size": number;
    "largeFile": boolean;
    "modifiedAt": string;
    "oldestEntry"?: string;
    "newestEntry"?: string;
}

/**
 * GetLogMaintenanceThresholds exposes logmaint's constants to the
 * frontend rather than duplicating the numbers there — same
 * never-hardcode-what-the-backend-already-knows convention this app uses
 * for the site's leader-tunable EPGP settings.
 */
export interface LogMaintenanceThresholds {
    "sizeWarningBytes": number;
    "keepDays": number;
    "liveWriteWindowMs": number;
}

/**
 * LogTailStatus backs a small diagnostics display (remediation plan Phase
 * 2 task 2.5): the followed file's size, how much of it has actually been
 * read, and how many times the tailer had to reset (the log was cleared
 * or replaced) — visibility into whether incremental tailing is behaving,
 * without adding a UI dependency on internal/logtail's own types.
 */
export interface LogTailStatus {
    "path": string;
    "size": number;
    "bytesRead": number;
    "resets": number;
    "lastReadAt": string;
}

/**
 * PointValues wraps FetchPointValues' two lists into one Wails-friendly
 * return — Wails bindings only carry a single value plus a trailing
 * error, so a bare (ep, gp, error) signature silently drops gp from the
 * generated TS binding.
 */
export interface PointValues {
    "ep": officerapi$0.PointValue[] | null;
    "gp": officerapi$0.PointValue[] | null;
}

/**
 * RollSessionView is one /random roll-off as shown in the Rolls tab.
 */
export interface RollSessionView {
    "id": string;
    "min": number;
    "max": number;
    "itemName": string;
    "startedAt": string;
    "lastRollAt": string;
    "active": boolean;
    "rolls": RollView[] | null;
    "winners": string[] | null;
}

/**
 * RollView is one roll within a RollSessionView.
 */
export interface RollView {
    "roller": string;
    "value": number;
    "occurredAt": string;
    "duplicate": boolean;
}

/**
 * UpdateInfo wraps the built-in updater's Check result into what the
 * startup "you're on an old build" banner (App.tsx) needs — mirrors the
 * Phase 7 updatecheck.Info shape so the frontend didn't need reworking
 * past its import path.
 */
export interface UpdateInfo {
    "current": string;
    "latest": string;
    "available": boolean;
    "url": string;
}
