// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as officerapi$0 from "./internal/officerapi/models.js";

/**
 * AttendanceResult is what the frontend's Attendance tab renders into its
 * editable table — see the app's sketch (Name/Timestamp column layout).
 */
export interface AttendanceResult {
    "occurredAt": string;
    "zone": string;
    "names": string[] | null;
    "warnings": string[] | null;
}

/**
 * BidRow is one candidate bid for the frontend's editable review table.
 */
export interface BidRow {
    "characterName": string;
    "occurredAt": string;
    "tier": string;
    "ambiguous": boolean;
    "rawMessage": string;

    /**
     * an earlier bid from the same character, kept visible but not the default winner
     */
    "superseded": boolean;
}

/**
 * LedgerPage wraps FetchLedger's (rows, hasNext) pair into one
 * Wails-friendly return — same reason as PointValues above.
 */
export interface LedgerPage {
    "rows": officerapi$0.LedgerRow[] | null;
    "hasNext": boolean;
}

/**
 * PointValues wraps FetchPointValues' two lists into one Wails-friendly
 * return — Wails bindings only carry a single value plus a trailing
 * error, so a bare (ep, gp, error) signature silently drops gp from the
 * generated TS binding.
 */
export interface PointValues {
    "ep": officerapi$0.PointValue[] | null;
    "gp": officerapi$0.PointValue[] | null;
}
