// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as eqlogs$0 from "./internal/eqlogs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as officerapi$0 from "./internal/officerapi/models.js";

/**
 * AttendanceResult is what the frontend's Attendance tab renders into its
 * editable table — see the app's sketch (Name/Timestamp column layout).
 */
export interface AttendanceResult {
    "occurredAt": string;
    "zone": string;
    "names": string[] | null;
    "warnings": string[] | null;
}

/**
 * BidRound is the state of one bid round the Bids tab renders. While Live
 * is true the poller re-emits this on "bids:round" every few seconds as
 * tells arrive; End Round & Review (EndBidRound) freezes it (Live false)
 * and the officer edits/submits from there. Wrapping the rows in a struct
 * rather than returning a bare []BidRow also sidesteps the Wails "extra
 * return value silently dropped" gotcha for the StartedAt/Live fields.
 */
export interface BidRound {
    "itemName": string;
    "startedAt": string;
    "rows": BidRow[] | null;
    "live": boolean;
}

/**
 * BidRow is one candidate bid for the frontend's editable review table.
 */
export interface BidRow {
    "characterName": string;
    "occurredAt": string;
    "tier": string;
    "ambiguous": boolean;
    "rawMessage": string;

    /**
     * an earlier bid from the same character, kept visible but not the default winner
     */
    "superseded": boolean;
}

/**
 * GameDirInfo is what the Settings screen renders after the officer picks
 * their EverQuest folder: the folder itself, every character log found
 * under it, and which one the app is now following (the most recently
 * written — the character they're currently playing).
 */
export interface GameDirInfo {
    "gameDir": string;
    "logs": eqlogs$0.CharacterLog[] | null;
    "activePath": string;
    "activeChar": string;
    "activeServer": string;
}

/**
 * LedgerPage wraps FetchLedger's (rows, hasNext) pair into one
 * Wails-friendly return — same reason as PointValues above.
 */
export interface LedgerPage {
    "rows": officerapi$0.LedgerRow[] | null;
    "hasNext": boolean;
}

/**
 * PointValues wraps FetchPointValues' two lists into one Wails-friendly
 * return — Wails bindings only carry a single value plus a trailing
 * error, so a bare (ep, gp, error) signature silently drops gp from the
 * generated TS binding.
 */
export interface PointValues {
    "ep": officerapi$0.PointValue[] | null;
    "gp": officerapi$0.PointValue[] | null;
}

/**
 * UpdateInfo wraps the built-in updater's Check result into what the
 * startup "you're on an old build" banner (App.tsx) needs — mirrors the
 * Phase 7 updatecheck.Info shape so the frontend didn't need reworking
 * past its import path.
 */
export interface UpdateInfo {
    "current": string;
    "latest": string;
    "available": boolean;
    "url": string;
}
