// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {officerapi} from '../models';
import {config} from '../models';

export function CaptureAttendance():Promise<main.AttendanceResult>;

export function CaptureBids(arg1:string):Promise<Array<main.BidRow>>;

export function FetchKnownItems():Promise<Array<string>>;

export function FetchLedger(arg1:string,arg2:string,arg3:number):Promise<main.LedgerPage>;

export function FetchPointValues():Promise<main.PointValues>;

export function FetchRoster():Promise<Array<officerapi.Character>>;

export function FetchTotals(arg1:string):Promise<Array<officerapi.TotalsRow>>;

export function GetLogPath():Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function LinkCharacter(arg1:string,arg2:any):Promise<officerapi.Character>;

export function OpenAppKeyPage():Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SelectLogFile():Promise<string>;

export function SubmitAttendance(arg1:string,arg2:string,arg3:Array<string>):Promise<officerapi.AttendanceResponse>;

export function SubmitBids(arg1:string,arg2:Array<officerapi.BidEntry>):Promise<officerapi.BidsResponse>;

export function SubmitManualEntry(arg1:officerapi.ManualEntryRequest):Promise<void>;

export function TestConnection():Promise<number>;
