// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureAttendance() {
  return window['go']['main']['App']['CaptureAttendance']();
}

export function CaptureBids(arg1) {
  return window['go']['main']['App']['CaptureBids'](arg1);
}

export function FetchKnownItems() {
  return window['go']['main']['App']['FetchKnownItems']();
}

export function FetchLedger(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchLedger'](arg1, arg2, arg3);
}

export function FetchPointValues() {
  return window['go']['main']['App']['FetchPointValues']();
}

export function FetchRoster() {
  return window['go']['main']['App']['FetchRoster']();
}

export function FetchTotals(arg1) {
  return window['go']['main']['App']['FetchTotals'](arg1);
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function OpenAppKeyPage() {
  return window['go']['main']['App']['OpenAppKeyPage']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectLogFile() {
  return window['go']['main']['App']['SelectLogFile']();
}

export function SubmitAttendance(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitAttendance'](arg1, arg2, arg3);
}

export function SubmitBids(arg1, arg2) {
  return window['go']['main']['App']['SubmitBids'](arg1, arg2);
}

export function SubmitManualEntry(arg1) {
  return window['go']['main']['App']['SubmitManualEntry'](arg1);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}
