// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {officerapi} from '../models';
import {config} from '../models';

export function CaptureAttendance():Promise<main.AttendanceResult>;

export function CaptureBids(arg1:string):Promise<Array<main.BidRow>>;

export function FetchKnownItems():Promise<Array<string>>;

export function FetchRoster():Promise<Array<officerapi.Character>>;

export function GetLogPath():Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function OpenAppKeyPage():Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SelectLogFile():Promise<string>;

export function SubmitAttendance(arg1:string,arg2:string,arg3:Array<string>):Promise<officerapi.AttendanceResponse>;

export function SubmitBids(arg1:string,arg2:Array<officerapi.BidEntry>):Promise<officerapi.BidsResponse>;

export function TestConnection():Promise<number>;
